    # set.seed(1)
# logisticModel <- glm(Creditability ~ Account.Ba, family = {3:gaussian}, data)
install.packages("aod")
install.packages("ggplot2")
library(aod)
library(ggplot2)
mydata <- read.csv("https://stats.idre.ucla.edu/stat/data/binary.csv")
head(mydata)
View(mydata)
summary(mydata)
sapply(mydata,sd)
xtabs(~admit + rank, data = mydata)
install.packages("dplyr")
library(dplyr, help, pos = 2, lib.loc = NULL)
glimpse(mydata)
install.packages("tidyverse")
library(tidyverse, help, pos = 2, lib.loc = NULL)
mydata$rank <- factor(mydata$rank)
mylogit <- glm(admit ~ gre + gpa + rank, family = binomial, data = mydata)
summary(mylogit)
confint(mylogit)
confint.default(mylogit)
library(aod, help, pos = 2, lib.loc = NULL)
wald.test(b = coef(mylogit), 
        Sigma = vcov(mylogit), Terms = 4:6)
l <- cbind(0, 0, 0, 1, -1, 0)
wald.test(b = coef(mylogit), 
          Sigma = vcov(mylogit), L = l)
exp(coef(mylogit))
exp(cbind(OR = coef(mylogit), confint(mylogit)))
newdata1 <- with(mydata, data.frame(gre = mean(gre), gpa = mean(gpa), rank = factor(1:4)))
newdata1
newdata1$rankP <- predict(mylogit, newdata = newdata1, type = "response")
newdata1    
newdata2 <- with(mydata, data.frame(gre = rep(seq(from = 200, to = 800, length.out = 100), 4), gpa = mean(gpa), rank = factor(rep(1:4, each = 100))))
newdata2$rankP <- predict(mylogit, newdata = newdata2, type = "response")
newdata2
ggplot(newdata2, aes(x = gre, y = rankP)) + geom_line(aes(colour = rank))
ggplot(mydata, aes(x = gre, y = admit)) + geom_point(aes(colour = rank), position = position_jitter(width = .1, height = .1))
